module.exports = {
  numeroDoDocumento: 'string',
  tipoDeConexao: 'string',
  classeDeConsumo: 'string',
  modalidadeTarifaria: 'string',
  historicoDeConsumo: [
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
    'number',
  ],
};
